### ISSUE TITLE
Twitter15、17数据集划分文件

### ISSUE THREAD

**Issue by Drew-youngking** [royal-dargon/MDSE#4]
作者您好，这么晚不好意思打扰您！最近研读完您的这篇《MODALITY-DEPENDENT SENTIMENTS EXPLORING FOR MULTI-MODAL SENTIMENT CLASSIFICATION》论文后，想复现您的这篇论文代码，想问一下能否提供Twitter15和17的数据集划分文件，非常感谢！学生不胜感激！

**Comment by royal-dargon** [comment]
邮件内已经回复了
